swagger: '2.0'
info:
  version: '1.0'
  title: Personnel Data
  description: 'API for reading and writing personnel data incl. data about attendances and absences'
host: api.personio.de
basePath: /v1
securityDefinitions:
  auth:
    type: apiKey
    name: Authorization
    in: header
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/company/employees':
    get:
      description: 'List Employees'
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/EmployeesResponse'
          examples:
            application/json:
              success: true
              data:
                - type: Employee
                  attributes:
                    id:
                      label: id
                      value: 83752
                    first_name:
                      label: First name
                      value: Andreas
                    last_name:
                      label: Last name
                      value: Anderson
                    email:
                      label: Email
                      value: andreas.anderson@demo.com
                    gender:
                      label: Gender
                      value: male
                    status:
                      label: Status
                      value: active
                    position:
                      label: Position
                      value: Online Marketing Specialist
                    supervisor:
                      label: Supervisor
                      value:
                        type: Employee
                        attributes:
                          id:
                            label: id
                            value: 423506
                          first_name:
                            label: First name
                            value: Max
                          last_name:
                            label: Last name
                            value: Mustermann
                          email:
                            label: Email
                            value: max.mustermann@example.org
                    employment_type:
                      label: Employment type
                      value: internal
                    weekly_working_hours:
                      label: Weekly hours
                      value: '40'
                    hire_date:
                      label: Hire date
                      value: '2012-02-01T00:00:00+0100'
                    contract_end_date:
                      label: Contract ends
                      value:
                    termination_date:
                      label: Termination date
                      value:
                    termination_type:
                      label: Termination type
                      value: ''
                    termination_reason:
                      label: Termination reason
                      value: ''
                    probation_period_end:
                      label: Probation period end
                      value: '2012-07-31T00:00:00+0200'
                    created_at:
                      label: created_at
                      value: '2016-10-20T16:15:55+0200'
                    last_modified_at:
                      label: Last modified
                      value: '2016-10-22T16:15:55+0200'
                    office:
                      label: Office
                      value:
                        type: Office
                        attributes:
                          name: Munich
                    department:
                      label: Department
                      value:
                        type: Department
                        attributes:
                          name: Marketing
                    cost_centers:
                      label: Cost center
                      value:
                      - type: CostCenter
                        attributes:
                          name: Cost Center One
                          id: 320
                          percentage: 50
                      - type: CostCenter
                        attributes:
                          name: Cost Center Two
                          id: 321
                          percentage: 50
                    fix_salary:
                      label: Fix salary
                      value: 4000
                    hourly_salary:
                      label: Hourly salary
                      value: 0
                    vacation_day_balance:
                      label: Vacation day balance
                      value: 28.5
                    last_working_day:
                      label: Last working day
                      value: '2017-02-28T00:00:00+0200'
                    dynamic_24407:
                      label: Titel
                      value: Dr
                    dynamic_21827:
                      label: IBAN
                      value: DE98 8989 9898 0000 8989 00
                    holiday_calendar:
                      label: 'Holiday Calendar'
                      value:
                        type: HolidayCalendar
                        attributes:
                          id: 931
                          name: 'DE (Hamburg) Feiertage'
                          country: DE
                          state: Hamburg
                    work_schedule:
                      label: 'Work Schedule'
                      value:
                        type: WorkSchedule
                        attributes:
                          id: 123
                          name: 'Standard Hours'
                          monday: '08:30'
                          tuesday: '08:30'
                          wednesday: '08:30'
                          thursday: '08:30'
                          friday: '06:00'
                          saturday: '00:00'
                          sunday: '00:00'
  '/company/employees/{employee_id}':
    get:
      description: 'Employee'
      parameters:
        - name: employee_id
          in: path
          required: true
          type: integer
          format: int32
          description: Numeric `id` of the employee
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/EmployeeResponse'
          examples:
            application/json:
              success: true
              data:
                type: Employee
                attributes:
                  id:
                    label: id
                    value: 83752
                  first_name:
                    label: First name
                    value: Andreas
                  last_name:
                    label: Last name
                    value: Anderson
                  email:
                    label: Email
                    value: andreas.anderson@demo.com
                  gender:
                    label: Gender
                    value: male
                  status:
                    label: Status
                    value: active
                  position:
                    label: Position
                    value: Online Marketing Specialist
                  supervisor:
                    label: Supervisor
                    value:
                      type: Employee
                      attributes:
                        id:
                          label: id
                          value: 423506
                        first_name:
                          label: First name
                          value: Max
                        last_name:
                          label: Last name
                          value: Mustermann
                        email:
                          label: Email
                          value: max.mustermann@example.org
                  employment_type:
                    label: Employment type
                    value: internal
                  weekly_working_hours:
                    label: Weekly hours
                    value: '40'
                  hire_date:
                    label: Hire date
                    value: '2012-02-01T00:00:00+0100'
                  contract_end_date:
                    label: Contract ends
                    value:
                  termination_date:
                    label: Termination date
                    value:
                  termination_type:
                    label: Termination type
                    value: ''
                  termination_reason:
                    label: Termination reason
                    value: ''
                  probation_period_end:
                    label: Probation period end
                    value: '2012-07-31T00:00:00+0200'
                  created_at:
                    label: created_at
                    value: '2016-10-20T16:15:55+0200'
                  last_modified_at:
                    label: Last modified
                    value: '2016-10-22T16:15:55+0200'
                  office:
                    label: Office
                    value:
                      type: Office
                      attributes:
                        name: Munich
                  department:
                    label: Department
                    value:
                      type: Department
                      attributes:
                        name: Marketing
                  cost_centers:
                    label: Cost center
                    value:
                    - type: CostCenter
                      attributes:
                        name: Cost Center One
                        id: 320
                        percentage: 50
                    - type: CostCenter
                      attributes:
                        name: Cost Center Two
                        id: 321
                        percentage: 50
                  fix_salary:
                    label: Fix salary
                    value: 4000
                  hourly_salary:
                    label: Hourly salary
                    value: 0
                  vacation_day_balance:
                    label: Vacation day balance
                    value: 28.5
                  last_working_day:
                    label: Last working day
                    value: '2017-02-28T00:00:00+0200'
                  dynamic_24407:
                    label: Titel
                    value: Dr
                  dynamic_21827:
                    label: IBAN
                    value: DE98 8989 9898 0000 8989 00
                  holiday_calendar:
                    label: 'Holiday Calendar'
                    value:
                      type: HolidayCalendar
                      attributes:
                        id: 931
                        name: 'DE (Hamburg) Feiertage'
                        country: DE
                        state: Hamburg
                  work_schedule:
                    label: 'Work Schedule'
                    value:
                      type: WorkSchedule
                      attributes:
                        id: 123
                        name: 'Standard Hours'
                        monday: '08:30'
                        tuesday: '08:30'
                        wednesday: '08:30'
                        thursday: '08:30'
                        friday: '06:00'
                        saturday: '00:00'
                        sunday: '00:00'

  '/company/attendances':
    get:
      description: >-
        This endpoint is responsible for fetching attendance data for the company employees.
        It is possible to paginate results, filter by period and/or specific employees.
        The result will contain a list of attendance periods, structured as defined here.
      produces:
        - application/json
      parameters:
        - name: start_date
          in: query
          required: true
          type: string
          format: date
          description: >-
            First day of the period to be queried.
            It is inclusive, so the day specified as start_date will also be considered on the results
        - name: end_date
          in: query
          required: true
          type: string
          format: date
          description: >-
            Last day of the period to be queried.
            It is inclusive, so the day specified as end_date will also be considered on the results.
        - name: employees
          in: query
          required: false
          type: array
          items:
            type: integer
          collectionFormat: multi
          description: >-
            A list of Personio employee identifiers to filter the results.
            Only those employees specified here will be returned.
        - name: limit
          in: query
          required: false
          type: integer
          minimum: 1
          default: 200
          description: >-
            Pagination attribute to limit how many attendances will be returned per page
        - name: offset
          in: query
          required: false
          type: integer
          minimum: 0
          default: 0
          description: 'Pagination attribute to identify which page you are requesting, by the form of telling an offset from the first record that would be returned.'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/AttendancePeriodsResponse'
          examples:
            application/json:
              success: true
              offset: 0
              limit: 200
              data:
              - id: 1234
                type: AttendancePeriod
                attributes:
                  employee: 325659
                  date: '2017-01-17'
                  start_time: '9:00'
                  end_time: '18:00'
                  break: 50
                  comment: I was productive as hell
                  is_holiday: false
                  is_on_time_off: false
              - id: 1235
                type: AttendancePeriod
                attributes:
                  employee: 325660
                  date: '2017-01-18'
                  start_time: '9:30'
                  end_time: '18:30'
                  break: 60
                  comment:
                  is_holiday: false
                  is_on_time_off: true
    post:
      description: >-
        This endpoint is responsible for adding attendance data for the company employees.
        It is possible to add attendances for one or many employees at the same time.
        The payload sent on the request should be a list of attendance periods, in the form of an array containing attendance period objects.
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        description: 'List of attendance periods to create'
        required: true
        schema:
          $ref: '#/definitions/NewAttendancePeriodRequest'
      responses:
        '200':
          description: 'The attendance periods were created successfully'
          schema:
            $ref: '#/definitions/NewAttendancePeriodResponse'
          examples:
            application/json:
              success: true
              data:
                message: 'success'
        '400':
          description: 'Invalid request'
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              success: true
              error:
                code: 400
                message: 'Error when trying to insert Attendances periods rows'
  '/company/attendances/{id}':
    delete:
      description: >-
        This endpoint is responsible for deleting attendance data for the company employees.
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 'ID of the attendance period to delete'
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: 'Success response'
          schema:
            $ref: '#/definitions/Response'
          examples:
             application/json:
              success: true
              data:
                message: 'The attendance period was deleted.'
        '404':
          description: 'Not found response'
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              success: false
              error:
                code: 404
                message: 'The attendance period was not found.'
    patch:
      description: >-
        This endpoint is responsible for updating attendance data for the company employees.
        Attributes are not required and if not specified, the current value will be used.
        It is not possible to change the employee id.
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 'ID of the attendance period to update'
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: 'attendance period data to update'
          required: true
          schema:
            $ref: '#/definitions/UpdateAttendancePeriodRequest'
      responses:
        '200':
          description: 'Success response'
          schema:
            $ref: '#/definitions/Response'
          examples:
             application/json:
              success: true
              data:
                message: 'The attendance period was updated.'
        '404':
          description: 'Not found response'
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              success: false
              error:
                code: 404
                message: 'The attendance period was not found.'


  '/company/time-off-types':
    get:
      description: >-
        Provides a list of available time-off types, for example 'Paid vacation', 'Parental leave' or 'Home office'
      produces:
        - application/json
      parameters:
        - name: limit
          in: query
          required: false
          type: integer
          minimum: 1
          default: 200
          description: >-
            Pagination attribute to limit how many records will be returned per page
        - name: offset
          in: query
          required: false
          type: integer
          minimum: 0
          default: 0
          description: 'Pagination attribute to identify which page you are requesting, by the form of telling an offset from the first record that would be returned.'
      responses:
        200:
          description: ''
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: array
                items:
                  $ref: '#/definitions/TimeOffTypeResource'
          examples:
            application/json:
              success: true
              data:
              - id: 1234
                type: TimeOffType
                attributes:
                  name: 'Paid vacation'
              - id: 1235
                type: TimeOffType
                attributes:
                  name: 'Home office'

  '/company/time-offs':
    get:
      description: >-
        This endpoint is responsible for fetching absence data for the company employees.
        It is possible to paginate results, filter by period and/or specific employees.
        The result will contain a list of absence periods, structured as defined here.
      produces:
        - application/json
      parameters:
        - name: start_date
          in: query
          required: false
          type: string
          format: date
          description: >-
            First day of the period to be queried.
            It is inclusive, so the day specified as start_date will also be considered on the results
        - name: end_date
          in: query
          required: false
          type: string
          format: date
          description: >-
            Last day of the period to be queried.
            It is inclusive, so the day specified as end_date will also be considered on the results.
        - name: employees
          in: query
          required: false
          type: array
          items:
            type: integer
          collectionFormat: multi
          description: >-
            A list of Personio employee identifiers to filter the results.
            Only those employees specified here will be returned.
        - name: limit
          in: query
          required: false
          type: integer
          minimum: 1
          default: 200
          description: >-
            Pagination attribute to limit how many attendances will be returned per page
        - name: offset
          in: query
          required: false
          type: integer
          minimum: 0
          default: 0
          description: 'Pagination attribute to identify which page you are requesting, by the form of telling an offset from the first record that would be returned.'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/AbsencePeriodsResponse'
          examples:
            application/json:
              success: true
              data:
              - type: TimeOffPeriod
                attributes:
                  id: 12345
                  status: approved
                  start_date: '2017-12-27T00:00:00+0100'
                  end_date: '2017-12-29T00:00:00+0100'
                  days_count: 3
                  half_day_start: 0
                  half_day_end: 0
                  time_off_type:
                    type: TimeOffType
                    attributes:
                      id: 54321
                      name: Vacation
                  employee:
                    type: Employee
                    attributes:
                      id:
                        label: id
                        value: 4567
                      first_name:
                        label: First name
                        value: Michael
                      last_name:
                        label: Last name
                        value: Miller
                      email:
                        label: Email
                        value: michael.miller@demo.com
                  certificate:
                    status: not-required
                  created_at: '2017-01-17T10:32:18+0100'
    post:
      description: >-
        This endpoint is responsible for adding absence data for the company employees.
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: 'Absence period to create'
          required: true
          schema:
            $ref: '#/definitions/CreateTimeOffPeriodRequest'
      responses:
        '201':
          description: 'The absence period was created successfully'
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/CreateTimeOffPeriodResponse'
          examples:
            application/json:
              success: true
              data:
                type: TimeOffPeriod
                attributes:
                  id: 12345
                  status: approved
                  start_date: '2017-12-27T00:00:00+0100'
                  end_date: '2017-12-29T00:00:00+0100'
                  days_count: 3
                  half_day_start: 0
                  half_day_end: 0
                  time_off_type:
                    type: TimeOffType
                    attributes:
                      id: 54321
                      name: Vacation
                  employee:
                    type: Employee
                    attributes:
                      id:
                        label: id
                        value: 4567
                      first_name:
                        label: First name
                        value: Michael
                      last_name:
                        label: Last name
                        value: Miller
                      email:
                        label: Email
                        value: michael.miller@demo.com
                  certificate:
                    status: not-required
                  created_at: '2017-01-17T10:32:18+0100'
        '422':
          description: 'Validation error'
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              success: false
              error:
                code: 0
                message: 'The given data failed to pass validation.'
                error_data: '{...}'

        '404':
          description: 'Employee or Absence type not found'
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              success: false
              error:
                code: 0
                message: 'Something went wrong'

        '400':
          description: 'Invalid request'
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              success: false
              error:
                code: 400
                message: 'Error when trying to insert absence period'
  '/company/time-offs/{id}':
    delete:
      description: >-
        This endpoint is responsible for deleting absence period data for the company employees.
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 'ID of the absence period to delete'
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: 'Success response'
          schema:
            $ref: '#/definitions/Response'
          examples:
             application/json:
              success: true
              data:
                message: 'The absence period was deleted.'
        '404':
          description: 'Not found response'
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              success: false
              error:
                code: 404
                message: 'The absence period was not found.'
    get:
      description: 'Absence Period'
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
          description: Numeric `id` of the absence period
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/AbsencePeriodResponse'
          examples:
            application/json:
              success: true
              data:
                type: TimeOffPeriod
                attributes:
                  id: 12345
                  status: approved
                  start_date: '2017-12-27T00:00:00+0100'
                  end_date: '2017-12-29T00:00:00+0100'
                  days_count: 3
                  half_day_start: 0
                  half_day_end: 0
                  time_off_type:
                    type: TimeOffType
                    attributes:
                      id: 45678
                      name: Vacation
                  employee:
                    type: Employee
                    attributes:
                      id:
                        label: id
                        value: 2367
                      first_name:
                        label: First name
                        value: Michael
                      last_name:
                        label: Last name
                        value: Miller
                      email:
                        label: Email
                        value: michael.miller@demo.com
                  certificate:
                    status: not-required
                  created_at: '2017-01-17T10:32:18+0100'
definitions:
  Response:
    title: Default response object
    type: object
    properties:
      success:
        type: boolean
      data:
        type: object
    required:
      - success
      - data
  ErrorResponse:
    title: Default error response
    type: object
    properties:
      success:
        type: boolean
      error:
        type: object
        properties:
          code:
            type: integer
          message:
            type: string
    required:
      - success
      - error
  Attribute:
    type: object
    properties:
      label:
        type: string
      value:
        type: object
    required:
      - label
      - value
  Office:
    type: object
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        type: object
        properties:
          'type':
            type: string
          attributes:
            type: object
            properties:
              name:
                type: string
  Department:
    type: object
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        type: object
        properties:
          'type':
            type: string
          attributes:
            type: object
            properties:
              name:
                type: string
  CostCenters:
    type: object
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        type: array
        items:
          type: object
          properties:
            'type':
              type: string
            attributes:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  id:
                    type: number
                  percentage:
                    type: number
  HolidayCalendar:
    type: object
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        type: object
        properties:
          'type':
            type: string
          attributes:
            type: object
            properties:
              id:
                type: number
              name:
                type: string
              country:
                type: string
              state:
                type: string
  WorkSchedule:
    type: object
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        type: object
        properties:
          'type':
            type: string
          attributes:
            type: object
            properties:
              id:
                type: number
              name:
                type: string
              monday:
                type: string
                pattern: '^\d\d:\d\d$'
              tuesday:
                type: string
                pattern: '^\d\d:\d\d$'
              wednesday:
                type: string
                pattern: '^\d\d:\d\d$'
              thursday:
                type: string
                pattern: '^\d\d:\d\d$'
              friday:
                type: string
                pattern: '^\d\d:\d\d$'
              saturday:
                type: string
                pattern: '^\d\d:\d\d$'
              sunday:
                type: string
                pattern: '^\d\d:\d\d$'
  Supervisor:
    type: object
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        $ref: '#/definitions/Employee'
  Employee:
    type: object
    required:
      - type
      - attributes
    properties:
      'type':
        type: string
      attributes:
        type: array
        items:
          type: object
          properties:
            id:
              $ref: '#/definitions/Attribute'
            first_name:
              $ref: '#/definitions/Attribute'
            last_name:
              $ref: '#/definitions/Attribute'
            email:
              $ref: '#/definitions/Attribute'
            gender:
              $ref: '#/definitions/Attribute'
            status:
              $ref: '#/definitions/Attribute'
            position:
              $ref: '#/definitions/Attribute'
            supervisor:
              $ref: '#/definitions/Supervisor'
            employment_type:
              $ref: '#/definitions/Attribute'
            weekly_working_hours:
              $ref: '#/definitions/Attribute'
            hire_date:
              $ref: '#/definitions/Attribute'
            contract_end_date:
              $ref: '#/definitions/Attribute'
            termination_date:
              $ref: '#/definitions/Attribute'
            termination_type:
              $ref: '#/definitions/Attribute'
            termination_reason:
              $ref: '#/definitions/Attribute'
            probation_period_end:
              $ref: '#/definitions/Attribute'
            created_at:
              $ref: '#/definitions/Attribute'
            fix_salary:
              $ref: '#/definitions/Attribute'
            hourly_salary:
              $ref: '#/definitions/Attribute'
            vacation_day_balance:
              $ref: '#/definitions/Attribute'
            office:
              $ref: '#/definitions/Office'
            department:
              $ref: '#/definitions/Department'
            cost_centers:
              $ref: '#/definitions/CostCenters'
            holiday_calendar:
              $ref: '#/definitions/HolidayCalendar'
            work_schedule:
              $ref: '#/definitions/WorkSchedule'
  EmployeesResponse:
    title: List of Employees
    allOf:
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          data:
            type: array
            items:
              type: object
              allOf:
                - $ref: '#/definitions/Employee'
  EmployeeResponse:
    title: Employee
    allOf:
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          data:
            type: object
            allOf:
              - $ref: '#/definitions/Employee'
  AttendancePeriodsResponse:
    title: List All Attenance Periods response
    type: object
    allOf:
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          offset:
            type: integer
          limit:
            type: integer
          data:
            type: array
            items:
              type: object
              required:
                - id
                - type
                - attributes
              properties:
                'id':
                  type: integer
                'type':
                  type: string
                attributes:
                  type: array
                  items:
                    type: object
                    required:
                      - employee
                      - date
                      - start_time
                      - end_time
                      - break
                      - comment
                      - is_holiday
                      - is_on_time_off
                    properties:
                      employee:
                        type: integer
                      date:
                        type: string
                        format: date
                      start_time:
                        type: string
                        pattern: '^\d\d:\d\d$'
                      end_time:
                        type: string
                        pattern: '^\d\d:\d\d$'
                      break:
                        type: integer
                      comment:
                        type: string
                      is_holiday:
                        type: boolean
                      is_on_time_off:
                        type: boolean
  UpdateAttendancePeriodRequest:
    title: Update an existing attendance period
    type: object
    properties:
      date:
        type: string
        format: date
        description: 'Attendance date as YYYY-MM-DD'
      start_time:
        type: string
        pattern: '^\d\d:\d\d$'
        description: 'Start time as HH:MM'
      end_time:
        type: string
        pattern: '^\d\d:\d\d$'
        description: 'End time as HH:MM'
      break:
        type: integer
        format: int32
        description: 'Break in minutes'
      comment:
        type: string
        description: 'Optional comment'
    example:
      date: '2019-03-17'
      start_time: '9:00'
      end_time: '12:00'
      break: 35
      comment: null

  NewAttendancePeriodRequest:
    title: Create a New Attendance Period request
    type: object
    properties:
      attendances:
        type: array
        items:
          type: object
          properties:
            employee:
              type: integer
              description: 'Employee identifier'
            date:
              type: string
              format: date
              description: 'Attendance date as YYYY-MM-DD'
            start_time:
              type: string
              pattern: '^\d\d:\d\d$'
              description: 'Start time as HH:MM'
            end_time:
              type: string
              pattern: '^\d\d:\d\d$'
              description: 'End time as HH:MM'
            break:
              type: integer
              format: int32
              description: 'Break in minutes'
            comment:
              type: string
              description: 'Optional comment'
          required:
            - employee
            - date
            - start_time
            - end_time
            - break
            - comment
    example:
      attendances:
        - employee: 1234
          date: '2017-01-18'
          start_time: '8:00'
          end_time: '18:00'
          break: 120
          comment:
        - employee: 1235
          date: '2017-01-17'
          start_time: '9:00'
          end_time: '12:00'
          break: 35
          comment: I was productive as hell

  NewAttendancePeriodResponse:
    type: object
    allOf:
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          data:
            type: object
            properties:
              message:
                type: string

  TimeOffTypeResource:
    title: 'Type of time-off resource'
    type: object
    properties:
      id:
        type: integer
        description: 'identifier'
      type:
        type: string
        enum:
          - 'TimeOffType'
        description: 'Time-off type resource name'
      attributes:
        type: object
        properties:
          name:
            type: string

  CreateTimeOffPeriodRequest:
    title: 'Create time-off periods'
    type: object
    properties:
      employee_id:
        type: integer
        description: 'Employee identifier'
      time_off_type_id:
        type: integer
        description: 'Time-off type identifier'
      start_date:
        type: string
        format: date
        description: 'Absence start date as YYYY-MM-DD'
      end_date:
        type: string
        format: date
        description: 'Absence end date as YYYY-MM-DD'
      half_day_start:
        type: boolean
        description: 'Weather the start date is a half-day off'
      half_day_end:
        type: boolean
        description: 'Weather the end date is a half-day off'
      comment:
        type: string
        description: 'Optional comment'
    required:
      - employee_id
      - time_off_type_id
      - start_date
      - end_date
      - half_day_start
      - half_day_end

  CreateTimeOffPeriodResponse:
    title: 'Time period when an employee is not available.'
    allOf:
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          data:
            type: object
            properties:
              type:
                type: string
                enum:
                  - 'TimeOffPeriod'
                description: 'Time-off period resource name'
              attributes:
                properties:
                  'id':
                    type: integer
                  status:
                    type: string
                  start_date:
                    type: string
                  end_date:
                    type: string
                  days_count:
                    type: number
                  half_day_start:
                    type: number
                  half_day_end:
                    type: number
                  time_off_type:
                    type: object
                    properties:
                      type:
                        type: string
                      attributes:
                        type: array
                        items:
                          type: object
                          properties:
                            'id':
                              type: integer
                            name:
                              type: string
                  employee:
                    type: object
                    properties:
                      type:
                        type: string
                      attributes:
                        type: array
                        items:
                          type: object
                          properties:
                            'id':
                              type: integer
                            first_name:
                              type: string
                            last_name:
                              type: string
                            email:
                              type: string
                  certificate:
                    type: object
                    properties:
                      status:
                        type: string
                  created_at:
                    type: string

  AbsencePeriodsResponse:
    title: List All Absence Periods response
    type: object
    allOf:
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          data:
            type: object
            required:
              - type
              - attributes
            properties:
              'type':
                type: string
              attributes:
                type: array
                items:
                  type: object
                  properties:
                    'id':
                      type: integer
                    status:
                      type: string
                    start_date:
                      type: string
                    end_date:
                      type: string
                    days_count:
                      type: number
                    half_day_start:
                      type: number
                    half_day_end:
                      type: number
                    time_off_type:
                      type: object
                      properties:
                        type:
                          type: string
                        attributes:
                          type: array
                          items:
                            type: object
                            properties:
                              'id':
                                type: integer
                              name:
                                type: string
                    employee:
                      type: object
                      properties:
                        type:
                          type: string
                        attributes:
                          type: array
                          items:
                            type: object
                            properties:
                              'id':
                                type: integer
                              first_name:
                                type: string
                              last_name:
                                type: string
                              email:
                                type: string
                    certificate:
                      type: object
                      properties:
                        status:
                          type: string
                    created_at:
                      type: string
  AbsencePeriodResponse:
    type: object
